### ISSUE TITLE
CreateHierarchy

### ISSUE THREAD

**Issue by aorgish** [v235/EpamTasks#25]
https://github.com/v235/EpamTasks/blob/master/05-LinqToXml/LinqToXml/LinqToXml.cs#L20-L28
Тут очень тяжело понять, что к чему. А если придется изменять что-то, то много времени уйдет. Для создания XML лучше всегда пользоваться functional constructor: https://msdn.microsoft.com/en-us/library/mt693049.aspx

**Comment by vitali-pimenau** [comment]
Сделал через конструктор и изменил код теперь намного проще.
