### ISSUE TITLE
FindChannelsIds

### ISSUE THREAD

**Issue by aorgish** [v235/EpamTasks#26]
https://github.com/v235/EpamTasks/blob/master/05-LinqToXml/LinqToXml/LinqToXml.cs#L119
Тут неудачный вариант с приведением. Можно сделать намного проще: `(int)c.Attribute("id")` . Для получения значений аттрибутов и элементов не нужно обращаться к Value, достаточно сразу привести к нужному типу. Подробнее тут: https://msdn.microsoft.com/en-us/library/mt693107.aspx

**Comment by vitali-pimenau** [comment]
Всё переделал, так реально лучше.
