### ISSUE TITLE
ReadPlanetInfoFromXlsx

### ISSUE THREAD

**Issue by aorgish** [v235/EpamTasks#28]
https://github.com/v235/EpamTasks/blob/master/07-IO%20Streams/IOStreams/TestTasks.cs#L31-L52
Самое страшное - что вызовы GetStream() не закрываются, как минимум в using это надо оборачивать. Потом копипаст кода new Uri(), XDocument.Load(package.GetPart(..).GetStream()), если код начинает повторяться, то лучше вынести его в отдельный метод

**Comment by vitali-pimenau** [comment]
Использовал using, избавился от копипаста и немного изменил код.
